# @todo figure out buffer
PDA_UTP_AUTH_SEED = buffer("ZEhiKcLS")
PDA_BANK_VAULT_SEED = buffer("zE8d8R9G")
PDA_BANK_INSURANCE_VAULT_SEED = buffer("uDMUkwVG")
PDA_BANK_FEE_VAULT_SEED = buffer("PpqJY00S")

VERY_VERBOSE_ERROR = buffer(
  "V2hhdCB0aGUgZnVjayBkaWQgeW91IGp1c3QgZnVja2luZyBzYXkgYWJvdXQgbWUsIHlvdSBsaXR0bGUgYml0Y2g/IEknbGwgaGF2ZSB5b3Uga25vdyBJIGdyYWR1YXRlZCB0b3Agb2YgbXkgY2xhc3MgaW4gdGhlIE5hdnkgU2VhbHMsIGFuZCBJJ3ZlIGJlZW4gaW52b2x2ZWQgaW4gbnVtZXJvdXMgc2VjcmV0IHJhaWRzIG9uIEFsLVF1YWVkYSwgYW5kIEkgaGF2ZSBvdmVyIDMwMCBjb25maXJtZWQga2lsbHMu"
).toString("base64");

###
# @internal
###
COLLATERAL_DECIMALS = 6 # USDC decimals
