[package]
name = "marginfi-cpi"
version = "0.1.0"
edition = "2021"

[features]
default = ["cpi", "mainnet-beta"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
mainnet-beta = []

[dependencies]
anchor-gen = "0.3.0"
anchor-lang = ">=0.24.2"
