name: main
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'     
        required: true
        default: 'latest-devnet' 
        type: choice
        options:
        - latest-mainnet
        - latest-devnet
        - latest-test
  pull_request:
    branches:
      - "*"
jobs:
  build-crank-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts
    env: 
      PACKAGE: marginfi-crank-bot
      VERSION: ${{ inputs.tag }}
    steps:
      - uses: actions/checkout@v2  
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-east1-docker.pkg.dev
      - name: Build Docker Image
        run: docker build --platform linux/amd64 -t us-east1-docker.pkg.dev/marginfi-dev/main/$PACKAGE:$VERSION . --build-arg package_name=$PACKAGE
      - name: Push Docker Image
        run: docker push us-east1-docker.pkg.dev/marginfi-dev/main/$PACKAGE:$VERSION
  build-interest-rate-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts
    env: 
      PACKAGE: marginfi-interest-rate-accumulator-bot
      VERSION: ${{ inputs.tag }}
    steps:
      - uses: actions/checkout@v2  
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-east1-docker.pkg.dev
      - name: Build Docker Image
        run: docker build --platform linux/amd64 -t us-east1-docker.pkg.dev/marginfi-dev/main/$PACKAGE:$VERSION . --build-arg package_name=$PACKAGE
      - name: Push Docker Image
        run: docker push us-east1-docker.pkg.dev/marginfi-dev/main/$PACKAGE:$VERSION
  build-liquidator-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts
    env: 
      PACKAGE: marginfi-liquidator-bot
      VERSION: ${{ inputs.tag }}
    steps:
      - uses: actions/checkout@v2  
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-east1-docker.pkg.dev
      - name: Build Docker Image
        run: docker build --platform linux/amd64 -t us-east1-docker.pkg.dev/marginfi-dev/main/$PACKAGE:$VERSION . --build-arg package_name=$PACKAGE
      - name: Push Docker Image
        run: docker push us-east1-docker.pkg.dev/marginfi-dev/main/$PACKAGE:$VERSION