name: python-marginpy-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  name: marginpy
  python_version: "3.9"
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      python-marginpy: ${{steps.check-if-files-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
      - name: Check if any file changed in list provided
        id: check-if-files-changed
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            python/marginpy

  macos_x86_64:
    runs-on: macos-latest
    if: needs.changed_files.outputs.python-marginpy == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
          architecture: x64
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      - uses: Swatinem/rust-cache@v1
      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist -m python/marginpy/Cargo.toml
      - name: Install built wheel and test
        run: |
          pip install pytest based58 pybip39
          pip install ${{ env.name }} --find-links dist --force-reinstall
          pytest -vv -m unit

  windows:
    runs-on: windows-latest
    if: needs.changed_files.outputs.python-marginpy == 'true'
    strategy:
      matrix:
        target: [x64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
          architecture: ${{ matrix.target }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      - uses: Swatinem/rust-cache@v1
      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -m python/marginpy/Cargo.toml
      - name: Install built wheel and test
        run: |
          python -m pip install pytest based58 pybip39
          python -m pip install ${{ env.name }} --find-links dist --force-reinstall
          python -m pytest -vv -m unit

  linux:
    runs-on: ubuntu-latest
    if: needs.changed_files.outputs.python-marginpy == 'true'
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}
          architecture: x64
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      - uses: Swatinem/rust-cache@v1
      - name: Build Wheels
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist -m python/marginpy/Cargo.toml
      - name: Install built wheel and test
        if: matrix.target == 'x86_64'
        run: |
          pip install pytest based58 pybip39
          pip install ${{ env.name }} --find-links dist --force-reinstall
          pytest -vv -m unit
